# Generated by Django 3.0.7 on 2020-12-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimage',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
